routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Category;
use App\Post;
use App\Setting;
use App\Tag;
use Illuminate\Support\Facades\Session;
use Spatie\Newsletter\NewsletterFacade as Newsletter;


Route::get('/',[
    'uses' => 'FrontEndController@index',
    'as' => 'index'
]);

Route::get('/article/{slug}',[
    'uses' => 'FrontEndController@article',
    'as' => 'post.view'
]);

Route::get('/category/{id}',[
    'uses'=>'FrontEndController@category',
    'as'=>'category.filter'
])->where('id','[0-9]+');

Route::get('/category/{slug}',[
    'uses'=>'FrontEndController@view',
    'as'=>'category.view'
]);

Route::get('/tag/{id}',[
    'uses'=>'FrontEndController@tag',
    'as'=>'tag.posts'
])->where('id','[0-9]+');

Route::get('/result/{slug}',[
    'uses'=>'FrontEndController@view',
    'as'=>'category.view'
]);

Route::get('/search',function(){
    $posts = Post::where('title','like','%'.request('query').'%')->get();
    return view('result')
        ->with('title','Search')
        ->with('filter','Result: '.request('query'))
        ->with('filterData',$posts)
        ->with('categories',Category::take(5)->get())
        ->with('setting',Setting::first())
        ->with('tags',Tag::all());
});

Route::post('/newsletter',function(){

    $email = request('email');

    if(Newsletter::isSubscribed($email)){
        Session::flash('Info',"this email {{$email}} subscribe before");
    }else{
        if(Newsletter::subscribe($email)){
            Session::flash('Succeed','Thank you for subscribe');
        }else{
            Session::flash('Error','Fail to subscribe please try again latter');
        }
    }

    return redirect()->back();
});

Auth::routes();

Route::get('/admin', 'HomeController@index')->name('home');

Route::group(['prefix'=>'admin','middleware'=>'auth'],function(){

    Route::get('/post/trashed',[
        'uses' => 'PostsController@trashed',
        'as' => 'post.trashed'
    ]);
    Route::get('/post/restore/{id}',[
        'uses' => 'PostsController@restore',
        'as' => 'post.restore'
    ]);
    Route::post('/post/kill',[
        'uses' => 'PostsController@kill',
        'as' => 'post.kill'
    ]);
    Route::resource("/category","CategoriesController",['except' => 'show']);
    Route::resource('/post','PostsController',['except' => 'show']);
    Route::resource('/tag','TagsController',['except' => 'show']);
    Route::resource('/user','UsersController',[
        'except' => ['show','edit','update']
    ]);
    Route::resource('/profile','ProfilesController');

    Route::get('/setting',[
        'uses' => 'SettingsControllser@index',
        'as' => 'setting'
    ]);

    Route::post('/setting/update',[
        'uses' => 'SettingsControllser@update',
        'as' => 'setting.update'
    ]);
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Post extends Model
{
    use SoftDeletes;

    // Useing When Used Method Create() To Do Save
    protected $fillable = [
        'title', 'featured', 'content', 'category_id', 'slug', 'user_id'
    ];

    protected $dates = ['deleted_at'];

    public function category(){
        return $this->belongsTo('App\Category');
    }

    public function tags(){
        return $this->belongsToMany('App\Tag');
    }

    public function user(){
        return $this->belongsTo('App\User');
    }
}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Post;
use App\Tag;
use Auth;
use Illuminate\Http\Request;
use Session;

class PostsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        if(Auth::user()->admin){
            $posts = Post::paginate(10);
        }else{
            $posts = Post::where('user_id',Auth::id())->paginate(10);
        }
        return view('admin.posts.index')->with('posts',$posts);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $categories = Category::all();
        $tags = Tag::all();
        if($categories->count()==0 || $tags->count()==0){

            Session::flash('Info','You must have some category or tags to pull post');
            return redirect()->back();
        }

        return view('admin.posts.create')
            ->with('categories',$categories)
            ->with('tags',$tags);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $this->validate($request,[
            'title'=>'required|max:255',
            'featured' => 'required|image',
            'content' => 'required',
            'category_id' => 'required',
            'tags' => 'required'
        ]);

        $featured = $request->file('featured');
        $featured_new_name = time().$request->file('featured')->getClientOriginalName();
        $featured->move('uploads/posts',$featured_new_name);

        /*$post = new Post();

        $post->title = $request->input('title');
        $post->featured = $featured_new_name;
        $post->content = $request->input('content');
        $post->category_id = $request->input('category_id');*/

       $post = Post::create([
           'title' => $request->input('title'),
           'featured' => 'uploads/posts/'.$featured_new_name,
           'content' => $request->input('content'),
           'category_id' => $request->input('category_id'),
           'slug' => str_slug($request->input('title')),
           'user_id' => Auth::id()
       ]);


        if($post->exists){
            $post->tags()->attach($request->tags);
            Session::flash('Succeed',"Saved Successfully");
        }else{
            Session::flash('Error',"Operation Not Done");
        }

        return redirect()->route('post.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        if(Auth::user()->admin){
            $post = Post::find($id);
        }else{
            $post = Post::where(['user_id'=>Auth::id(),'id'=>$id])->first();
        }

        return view("admin.posts.edit")
            ->with('post',$post)
            ->with('categories',Category::all())
            ->with('tags',Tag::all());
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $this->validate($request,[
            'title'=>'required|max:255',
            'content' => 'required',
            'category_id' => 'required'
        ]);

        $post = Post::find($id);

        $post->title = $request->input('title');
        $post->content = $request->input('content');
        $post->category_id = $request->input('category_id');

        if($request->hasFile('featured')){
            $featured = $request->file('featured');
            $featured_new_name = time().$request->file('featured')->getClientOriginalName();
            $featured->move('uploads/posts',$featured_new_name);
            $post->featured = 'uploads/posts/'.$featured_new_name;
        }

        if($post->save()){
            $post->tags()->sync($request->tags);
            Session::flash('Succeed',"Saved Successfully");
        }else{
            Session::flash('Error',"Operation Not Done");
        }

        return redirect()->route('post.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        if(Auth::user()->admin){
            $post = Post::find($id);
        }else{
            $post = Post::where(['user_id'=>Auth::id(),'id'=>$id])->first();
        }

        if($post->delete()){
            Session::flash('Succeed',"Trashed Successfully");
        }else{
            Session::flash('Error',"Operation Not Done");
        }

        return redirect()->route('post.index');
    }

    public function trashed(){

        if(Auth::user()->admin){
            $posts = Post::onlyTrashed()->get();
        }else{
            $posts = Post::onlyTrashed()->where('user_id',Auth::id())->get();
        }

        return view('admin.posts.trashed')->with('posts',$posts);
    }

    public function kill(Request $request){

        $post = Post::withTrashed()->where('id',$request->id)->first();

        if($post->forceDelete()){
            Session::flash('Succeed',"Deleted Successfully");
        }else{
            Session::flash('Error',"Operation Not Done");
        }

        return redirect()->route('post.index');
    }

    public function restore($id){

        if(Auth::user()->admin){
            $post = Post::withTrashed()->where('id',$id)->first();
        }else{
            $post = Post::withTrashed()->where(['id'=>$id,'user_id'=>Auth::id()])->first();
        }

        if($post->restore()){
            Session::flash('Succeed',"Restored Successfully");
        }else{
            Session::flash('Error',"Operation Not Done");
        }

        return redirect()->route('post.index');
    }
}

resources/views/admin/posts/create.blade.php
@extends("layouts.app")

@section("content")

    @include("includes.errors")

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Create New Post</h3>
        </div>
        <div class="panel-body">

            <form action="{{route('post.store')}}" method="post" enctype="multipart/form-data" >
                {{csrf_field()}}

                <div class="form-group">
                    <label for="category_id">Category Name</label>
                    <select name="category_id" id="category_id" class="form-control">
                        <option value=""> -- Select One -- </option>
                        @foreach($categories as $category)
                            <option value="{{$category->id}}"
                            @if(old('category_id')==$category->id)
                                 selected
                            @endif
                            >{{$category->name_category}}</option>
                        @endforeach
                    </select>
                </div>

                <div class="form-group">
                    <label for="title">Title</label>
                    <input type="text" name="title" id="title" value="{{old('title')}}" class="form-control">
                </div>

                <div class="form-group">
                    <label for="title">Featured image</label>
                    <input type="file" name="featured" id="featured" class="form-control">
                </div>

                <div class="form-group">
                    <label for="content">Content</label>
                    <textarea name="content" id="content" cols="5" rows="3" class="form-control">{{old('content')}}</textarea>
                </div>

                <div class="form-group">
                    <label for="tags">Select Tags</label>
                    <div class="pre-scrollable">
                        @foreach($tags as $tag)
                            <div class="checkbox">
                                <label>

                                    <input type="checkbox" value="{{$tag->id}}" name="tags[]"

                                    @if(is_array(old('tags')) && in_array($tag->id,old('tags')))
                                        checked
                                    @endif

                                    >
                                    {{$tag->tag}}
                                </label>
                            </div>
                        @endforeach
                    </div>
                </div>

                <div class="form-group text-center">
                    <button type="submit" class="btn btn-default">Submit</button>
                 </div>

            </form>
        </div>
    </div>
@endsection

@section('stylesPut')
    <link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.8/summernote.css" rel="stylesheet">
@endsection

@section('scriptPut')
    <script src="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.8/summernote.js"></script>
    <script>
        $(document).ready(function() {
            $('#content').summernote();
        });
    </script>
@endsection

resources/views/admin/posts/edit.blade.php
@extends("layouts.app")

@section("content")

    @include("includes.errors")

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Edit Post</h3>
        </div>
        <div class="panel-body">

            <form action="{{route('post.update',['id'=>$post->id])}}" method="post" enctype="multipart/form-data" >
                {{csrf_field()}}
                {{ method_field('PUT') }}
                <div class="form-group">
                    <label for="category_id">Category Name</label>
                    <select name="category_id" id="category_id" class="form-control">
                        <option value=""> -- Select One -- </option>
                        @foreach($categories as $category)

                            <option
                                    value="{{$category->id}}"
                                    @if($category->id==$post->category_id)
                                    selected
                                    @endif
                            >{{$category->name_category}}</option>
                        @endforeach
                    </select>
                </div>

                <div class="form-group">
                    <label for="title">Title</label>
                    <input type="text" name="title" value="{{$post->title}}" id="title" class="form-control">
                </div>

                <div class="form-group">
                    <label for="title">Featured image</label>
                    <input type="file" name="featured" id="featured" class="form-control">
                </div>

                <div class="form-group">
                    <label for="content">Content</label>
                    <textarea name="content" id="content" cols="5" rows="3" class="form-control">{{$post->content}}</textarea>
                </div>

                <?php foreach($post->tags as $pTag) {$tagsId[]=$pTag->id;} ?>

                <div class="form-group">
                    <label for="tags">Select Tags</label>
                    <div class="pre-scrollable">
                        @foreach($tags as $tag)
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" value="{{$tag->id}}" name="tags[]"
                                       @if(in_array($tag->id,$tagsId))
                                           checked
                                       @endif
                                    >
                                    {{$tag->tag}}
                                </label>
                            </div>
                        @endforeach
                    </div>
                </div>

                <div class="form-group text-center">
                    <button type="submit" class="btn btn-default">Submit</button>
                 </div>

            </form>
        </div>
    </div>
@endsection

@section('stylesPut')
    <link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.8/summernote.css" rel="stylesheet">
@endsection

@section('scriptPut')
    <script src="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.8/summernote.js"></script>
    <script>
        $(document).ready(function() {
            $('#content').summernote();
        });
    </script>
@endsection

resources/views/admin/posts/index.blade.php
@extends("layouts.app")

@section("content")

    <div class="panel panel-default">
        <div class="panel-body">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th>Image</th>
                    <th>Category</th>
                    <th>Title</th>
                    <th colspan="2" width="15%">Action</th>
                </tr>
                </thead>
                <tbody>
                    @foreach($posts as $post)
                        <tr>
                            <td><img src="{{asset($post->featured)}}" width="50" height="50"></td>
                            <td>{{$post->category->name_category}}</td>
                            <td>{{$post->title}}</td>
                            <td>
                                <a href="{{route('post.edit',['id' => $post->id])}}" class="btn btn-xs btn-info"><i class="fa fa-pencil"></i> Update</a>
                            </td>
                            <td>
                                <form action="{{route("post.destroy",['id' => $post->id])}}" method="post" role="form" class="form-inline">
                                    {{ method_field('delete') }}
                                    {{ csrf_field() }}
                                    <button type="submit" class="btn btn-xs btn-danger"><i class="fa fa-trash-o"></i> Trash</button>
                                </form>
                            </td>
                        </tr>                        
                    @endforeach
                </tbody>
            </table>
        </div>
        <div class="panel-footer text-center ">
            {!! $posts->links() !!}
        </div>
    </div>
@endsection

resources/views/admin/posts/trashed.blade.php
@extends("layouts.app")

@section("content")

    <div class="panel panel-default">
        <div class="panel-body">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th>Image</th>
                    <th>Category</th>
                    <th>Title</th>
                    <th colspan="2" width="15%">Action</th>
                </tr>
                </thead>
                <tbody>
                    @foreach($posts as $post)
                        <tr>
                            <td><img src="{{asset($post->featured)}}" width="50" height="50"></td>
                            <td>{{$post->category->name_category}}</td>
                            <td>{{$post->title}}</td>
                            <td>
                                <a href="{{route('post.restore',['id'=>$post->id])}}" class="btn btn-xs btn-success"><i class="fa fa-window-restore"></i> Restore</a>
                            </td>
                            <td>
                                <form action="{{route("post.kill")}}" method="post" role="form" class="form-inline">
                                    {{ csrf_field() }}
                                    <input type="hidden" name="id" id="id" value="{{$post->id}}">
                                    <button type="submit" class="btn btn-xs btn-danger"><i class="fa fa-trash-o"></i> Delete</button>
                                </form>
                            </td>
                        </tr>                        
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection