routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Category;
use App\Post;
use App\Setting;
use App\Tag;
use Illuminate\Support\Facades\Session;
use Spatie\Newsletter\NewsletterFacade as Newsletter;


Route::get('/',[
    'uses' => 'FrontEndController@index',
    'as' => 'index'
]);

Route::get('/article/{slug}',[
    'uses' => 'FrontEndController@article',
    'as' => 'post.view'
]);

Route::get('/category/{id}',[
    'uses'=>'FrontEndController@category',
    'as'=>'category.filter'
])->where('id','[0-9]+');

Route::get('/category/{slug}',[
    'uses'=>'FrontEndController@view',
    'as'=>'category.view'
]);

Route::get('/tag/{id}',[
    'uses'=>'FrontEndController@tag',
    'as'=>'tag.posts'
])->where('id','[0-9]+');

Route::get('/result/{slug}',[
    'uses'=>'FrontEndController@view',
    'as'=>'category.view'
]);

Route::get('/search',function(){
    $posts = Post::where('title','like','%'.request('query').'%')->get();
    return view('result')
        ->with('title','Search')
        ->with('filter','Result: '.request('query'))
        ->with('filterData',$posts)
        ->with('categories',Category::take(5)->get())
        ->with('setting',Setting::first())
        ->with('tags',Tag::all());
});

Route::post('/newsletter',function(){

    $email = request('email');

    if(Newsletter::isSubscribed($email)){
        Session::flash('Info',"this email {{$email}} subscribe before");
    }else{
        if(Newsletter::subscribe($email)){
            Session::flash('Succeed','Thank you for subscribe');
        }else{
            Session::flash('Error','Fail to subscribe please try again latter');
        }
    }

    return redirect()->back();
});

Auth::routes();

Route::get('/admin', 'HomeController@index')->name('home');

Route::group(['prefix'=>'admin','middleware'=>'auth'],function(){

    Route::get('/post/trashed',[
        'uses' => 'PostsController@trashed',
        'as' => 'post.trashed'
    ]);
    Route::get('/post/restore/{id}',[
        'uses' => 'PostsController@restore',
        'as' => 'post.restore'
    ]);
    Route::post('/post/kill',[
        'uses' => 'PostsController@kill',
        'as' => 'post.kill'
    ]);
    Route::resource("/category","CategoriesController",['except' => 'show']);
    Route::resource('/post','PostsController',['except' => 'show']);
    Route::resource('/tag','TagsController',['except' => 'show']);
    Route::resource('/user','UsersController',[
        'except' => ['show','edit','update']
    ]);
    Route::resource('/profile','ProfilesController');

    Route::get('/setting',[
        'uses' => 'SettingsControllser@index',
        'as' => 'setting'
    ]);

    Route::post('/setting/update',[
        'uses' => 'SettingsControllser@update',
        'as' => 'setting.update'
    ]);
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    //
    public function posts(){
        return $this->hasMany('App\Post');
    }
}

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //

        return view("admin.categories.index")->with('categories',Category::paginate(10));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('admin.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $this->validate($request,[
            'name_category' => 'required'
        ]);

        $category = new Category();
        $category->name_category =  $request->name_category;
        $category->slug =  str_slug($request->name_category);
        if($category->save()){
            Session::flash('Succeed',"Saved Successfully");
        }else{
            Session::flash('Error',"Operation Not Done");
        }

        return redirect()->route('category.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $category = Category::find($id);

        return view("admin.categories.edit")->with('category',$category);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $this->validate($request,[
            'name_category' => 'required'
        ]);

        $category=Category::find($id);
        $category->name_category = $request->name_category;
        $category->slug =  str_slug($request->name_category);
        if($category->save()){
            Session::flash('Succeed',"Updated Successfully");
        }else{
            Session::flash('Error',"Operation Not Done");
        }

        return redirect()->route('category.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $category=Category::find($id);

        foreach ($category->posts as $post){
            //$post->delete();
            $post->forceDelete();
        }

        if($category->Delete()){
            Session::flash('Succeed',"Deleted Successfully");
        }else{
            Session::flash('Error',"Operation Not Done");
        }

        return redirect()->route('category.index');
    }
}

resources/views/admin/categories/create.blade.php
@extends("layouts.app")

@section("content")

    @include("includes.errors")

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Create New Category</h3>
        </div>
        <div class="panel-body">

            <form action="{{route('category.store')}}" method="post"  >
                {{csrf_field()}}

                <div class="form-group">
                    <label for="name_category">Category Name:</label>
                    <input type="text" name="name_category" id="name_category" class="form-control">
                </div>

                <div class="form-group text-center">
                    <button type="submit" class="btn btn-default">Submit</button>
                </div>

            </form>
        </div>
    </div>
@endsection

resources/views/admin/categories/edit.blade.php
@extends("layouts.app")

@section("content")

    @include("includes.errors")

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Edit Category</h3>
        </div>
        <div class="panel-body">

            <form action="{{route('category.update',['id'=>$category->id])}}" method="post"  >
                {{csrf_field()}}
                {{ method_field('PUT') }}
                <div class="form-group">
                    <label for="name_category">Category Name:</label>
                    <input type="text" name="name_category" value="{{$category->name_category}}" id="name_category" class="form-control">
                </div>

                <div class="form-group text-center">
                    <button type="submit" class="btn btn-default">Submit</button>
                </div>

            </form>
        </div>
    </div>
@endsection

resources/views/admin/categories/index.blade.php
@extends("layouts.app")

@section("content")


    <div class="panel panel-default">
        <div class="panel-body">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th>id</th>
                    <th>Category Name</th>
                    <th colspan="2" width="30%">Actions</th>
                </tr>
                </thead>
                <tbody>
                @foreach($categories as $category)
                    <tr>
                        <td>{{$category->id}}</td>
                        <td>{{$category->name_category}}</td>
                        <td>
                            <a href="{{route('category.edit',['id' => $category->id])}}" class="btn btn-xs btn-info"><i class="fa fa-pencil"></i> Update</a>
                        </td>
                        <td>
                            @if(Auth::user()->admin)
                            <form action="{{route("category.destroy",['id' => $category->id])}}" method="post" role="form" class="form-inline">
                                {{ method_field('delete') }}
                                {{ csrf_field() }}
                                <button type="submit" class="btn btn-xs btn-danger"><i class="fa fa-trash-o"></i> Delete</button>
                            </form>
                            @endif
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
        <div class="panel-footer text-center ">
            {!! $categories->links() !!}
        </div>
    </div>
@endsection