routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Category;
use App\Post;
use App\Setting;
use App\Tag;
use Illuminate\Support\Facades\Session;
use Spatie\Newsletter\NewsletterFacade as Newsletter;


Route::get('/',[
    'uses' => 'FrontEndController@index',
    'as' => 'index'
]);

Route::get('/article/{slug}',[
    'uses' => 'FrontEndController@article',
    'as' => 'post.view'
]);

Route::get('/category/{id}',[
    'uses'=>'FrontEndController@category',
    'as'=>'category.filter'
])->where('id','[0-9]+');

Route::get('/category/{slug}',[
    'uses'=>'FrontEndController@view',
    'as'=>'category.view'
]);

Route::get('/tag/{id}',[
    'uses'=>'FrontEndController@tag',
    'as'=>'tag.posts'
])->where('id','[0-9]+');

Route::get('/result/{slug}',[
    'uses'=>'FrontEndController@view',
    'as'=>'category.view'
]);

Route::get('/search',function(){
    $posts = Post::where('title','like','%'.request('query').'%')->get();
    return view('result')
        ->with('title','Search')
        ->with('filter','Result: '.request('query'))
        ->with('filterData',$posts)
        ->with('categories',Category::take(5)->get())
        ->with('setting',Setting::first())
        ->with('tags',Tag::all());
});

Route::post('/newsletter',function(){

    $email = request('email');

    if(Newsletter::isSubscribed($email)){
        Session::flash('Info',"this email {{$email}} subscribe before");
    }else{
        if(Newsletter::subscribe($email)){
            Session::flash('Succeed','Thank you for subscribe');
        }else{
            Session::flash('Error','Fail to subscribe please try again latter');
        }
    }

    return redirect()->back();
});

Auth::routes();

Route::get('/admin', 'HomeController@index')->name('home');

Route::group(['prefix'=>'admin','middleware'=>'auth'],function(){

    Route::get('/post/trashed',[
        'uses' => 'PostsController@trashed',
        'as' => 'post.trashed'
    ]);
    Route::get('/post/restore/{id}',[
        'uses' => 'PostsController@restore',
        'as' => 'post.restore'
    ]);
    Route::post('/post/kill',[
        'uses' => 'PostsController@kill',
        'as' => 'post.kill'
    ]);
    Route::resource("/category","CategoriesController",['except' => 'show']);
    Route::resource('/post','PostsController',['except' => 'show']);
    Route::resource('/tag','TagsController',['except' => 'show']);
    Route::resource('/user','UsersController',[
        'except' => ['show','edit','update']
    ]);
    Route::resource('/profile','ProfilesController');

    Route::get('/setting',[
        'uses' => 'SettingsControllser@index',
        'as' => 'setting'
    ]);

    Route::post('/setting/update',[
        'uses' => 'SettingsControllser@update',
        'as' => 'setting.update'
    ]);
});

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    //
    protected $fillable = ['tag'];

    public function posts(){
        return $this->belongsToMany('App\Post');
    }
}

app/Http/Controllers/TagsController.php
<?php

namespace App\Http\Controllers;

use App\Tag;
use Illuminate\Http\Request;
use Session;

class TagsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.tags.index')->with('tags',Tag::paginate(10));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.tags.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $this->validate($request,[
            'tag' => 'required'
        ]);

        $tag = Tag::create([
            'tag' => $request->input('tag')
        ]);

        if($tag->exists){
            Session::flash('Succeed',"Saved Successfully");
        }else{
            Session::flash('Error',"Operation Not Done");
        }

        return redirect()->route('tag.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('admin.tags.edit')->with('tag',Tag::find($id));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'tag' => 'required'
        ]);

        $tag = Tag::find($id);
        $tag->tag = $request->input('tag');

        if($tag->save()){
            Session::flash('Succeed',"Updated Successfully");
        }else{
            Session::flash('Error',"Operation Not Done");
        }

        return redirect()->route('tag.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if(Tag::destroy($id)>0){
            Session::flash('Succeed',"Deleted Successfully");
        }else{
            Session::flash('Error',"Operation Not Done");
        }

        return redirect()->route('tag.index');
    }
}

resources/views/admin/tags/create.blade.php
@extends("layouts.app")

@section("content")

    @include("includes.errors")

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Create New Tag</h3>
        </div>
        <div class="panel-body">

            <form action="{{route('tag.store')}}" method="post"  >
                {{csrf_field()}}

                <div class="form-group">
                    <label for="tag">Tag Name:</label>
                    <input type="text" name="tag" id="tag" class="form-control">
                </div>

                <div class="form-group text-center">
                    <button type="submit" class="btn btn-default">Submit</button>
                </div>

            </form>
        </div>
    </div>
@endsection

resources/views/admin/tags/edit.blade.php
@extends("layouts.app")

@section("content")

    @include("includes.errors")

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Edit Tag</h3>
        </div>
        <div class="panel-body">

            <form action="{{route('tag.update',['id'=>$tag->id])}}" method="post"  >
                {{csrf_field()}}
                {{ method_field('PUT') }}
                <div class="form-group">
                    <label for="tag">tag Name:</label>
                    <input type="text" name="tag" value="{{$tag->tag}}" id="tag" class="form-control">
                </div>

                <div class="form-group text-center">
                    <button type="submit" class="btn btn-default">Submit</button>
                </div>

            </form>
        </div>
    </div>
@endsection

resources/views/admin/tags/index.blade.php
@extends("layouts.app")

@section("content")
    <div class="panel panel-default">
        <div class="panel-body">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th>id</th>
                    <th>Tag Name</th>
                    <th colspan="2" width="30%">Actions</th>
                </tr>
                </thead>
                <tbody>
                @foreach($tags as $tag)
                    <tr>
                        <td>{{$tag->id}}</td>
                        <td>{{$tag->tag}}</td>
                        <td>
                            <a href="{{route('tag.edit',['id' => $tag->id])}}" class="btn btn-xs btn-info"><i class="fa fa-pencil"></i> Update</a>
                        </td>
                        <td>
                            @if(Auth::user()->admin)
                            <form action="{{route("tag.destroy",['id' => $tag->id])}}" method="post" role="form" class="form-inline">
                                {{ method_field('delete') }}
                                {{ csrf_field() }}
                                <button type="submit" class="btn btn-xs btn-danger"><i class="fa fa-trash-o"></i> Delete</button>
                            </form>
                            @endif
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
        <div class="panel-footer text-center ">
            {!! $tags->links() !!}
        </div>
    </div>
@endsection